import {
  zipIcon,
  ageIcon,
  HouseHoldIcon,
  homeTypeIcon,
  rentIcon,
  vehicleIcon,
  obligationIcon,
  healthcareIcon,
  incomeIcon,
} from '../utlis/Imports';

export const title = [
  {
    0: 'ZipCode',
    imageSrc: zipIcon,
  },
  {
    1: 'Age ',
    imageSrc: ageIcon,
  },
  {
    2: 'HouseHold',
    imageSrc: HouseHoldIcon,
  },
  {
    3: 'HomeType ',
    imageSrc: homeTypeIcon,
  },
  {
    4: 'Rent ',
    imageSrc: rentIcon,
  },
  {
    5: 'Vechicles ',
    imageSrc: vehicleIcon,
  },
  {
    6: 'Obligations ',
    imageSrc: obligationIcon,
  },
  {
    7: 'Obligations ',
    imageSrc: obligationIcon,
  },
  {
    8: 'Health Insurance ',
    imageSrc: healthcareIcon,
  },
  {
    9: 'Health Insurance ',
    imageSrc: healthcareIcon,
  },
  {
    10: 'Take Home ',
    imageSrc: incomeIcon,
  },
];

export const transformerData = {
  alcoholic_beverages: 'Groceries',
  cash_contributions: 'Charitable Giving',
  clothing_items_and_services: 'Clothing & Jewelry',
  education: 'Education',
  electricity: 'Utilities - Power Bill',
  fees_and_admissions: 'Fun & Leisure',
  food_home: 'Groceries',
  food_out: 'Dining Out',
  furniture_and_appliances: 'Home Appliances & Furniture',
  gasoline: 'Gasoline & EV-Charging',
  health_insurance: 'Health Insurance',
  heating_fuels_other: 'Utilities - Other',
  home_maintenance_and_repairs: 'Home Maintenance & Services',
  housekeeping_supplies: 'Home Maintenance & Services',
  life_and_personal_insurance: 'Life & Other Personal Insurance',
  media_hardware_and_services: 'Cable / Internet / Streaming',
  medical_services: 'Medical Spending',
  medical_supplies: 'Medical Spending',
  miscellaneous: 'Miscellaneous',
  mortgage_and_rent: 'Rent or Mortgage Payment',
  natural_gas: 'Utilities - Other',
  other_debt_payments: 'Other Debt Payments & Obligations',
  other_household_expenses: 'Home Maintenance & Services',
  other_lodging: 'Vacation & Other Lodging',
  personal_care: 'Personal Care Products and Services',
  personal_services: 'Babysitting / Preschool / Eldercare',
  pets: 'Pets',
  prescription_drugs: 'Medical Spending',
  public_and_other_transportation: 'Transportation Fares',
  reading: 'Miscellaneous',
  savings: 'Amount to Savings Each Period',
  telephone_services: 'Phone Services',
  tobacco_and_smoking: 'Miscellaneous',
  toys_and_hobbies: 'Fun & Leisure',
  vehicle_insurance: 'Car Insurance',
  vehicle_maintenance_and_repairs: 'Car Maintenance',
  vehicle_purchase_and_lease: 'Car Payments',
  water_and_public_services: 'Utilities - Other',
};

export const majorExpenseCategories = [
  'Rent or Mortgage Payment',
  'Health Insurance',
  'Car Payments',
  'Other Debt Payments & Obligations',
];

export const monthlyBillExpenseCategories = [
  'Charitable Giving',
  'Utilities - Power Bill',
  'Car Insurance',
  'Utilities - Other',
  'Cable / Internet / Streaming',
  'Phone Services',
];
export const otherExpenseCategories = [
  'Groceries',
  'Dining Out',
  'Gasoline & EV-Charging',
  'Fun & Leisure',
  'Clothing & Jewelry',
  'Medical Spending',
  'Home Maintenance & Services',
  'Medical Spending',
  'Miscellaneous',
  'Education',
  'Vacation & Other Lodging',
  'Car Maintenance',
  'Personal Care Products and Services',
  'Pets',
  'Transportation Fares',
  'Life & Other Personal Insurance',
  'Babysitting / Preschool / Eldercare',
];

export const categories = [
  'Groceries',
  'Charitable Giving',
  'Clothing & Jewelry',
  'Education',
  'Utilities - Power Bill',
  'Fun & Leisure',
  'Dining Out',
  'Home Appliances & Furniture',
  'Gasoline & EV-Charging',
  'Health Insurance',
  'Utilities - Other',
  'Home Maintenance & Services',
  'Life & Other Personal Insurance',
  'Cable / Internet / Streaming',
  'Medical Spending',
  'Miscellaneous',
  'Rent or Mortgage Payment',
  'Other Debt Payments & Obligations',
  'Vacation & Other Lodging',
  'Personal Care Products and Services',
  'Babysitting / Preschool / Eldercare',
  'Pets',
  'Transportation Fares',
  'Amount to Savings Each Period',
  'Phone Services',
  'Car Insurance',
  'Car Maintenance',
  'Car Payments',
];

export const needsCategories = [
  'Rent or Mortgage Payment',
  'Health Insurance',
  'Car Payments',
  'Other Debt Payments & Obligations',
  'Charitable Giving',
  'Utilities - Power Bill',
  'Car Insurance',
  'Utilities - Other',
  'Cable / Internet / Streaming',
  'Phone Services',
];
