export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';

export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAIL = 'LOGOUT_FAIL';

export const LENDING_REQUEST = 'LENDING_REQUEST';
export const LENDING_SUCCESS = 'LENDING_SUCCESS';
export const LENDING_RESET = 'LENDING_RESET';
export const LENDING_FAIL = 'LENDING_FAIL';

export const DEMOGRAPHICS_REQUEST = 'DEMOGRAPHICS_REQUEST';
export const DEMOGRAPHICS_SUCCESS = 'DEMOGRAPHICS_SUCCESS';
export const DEMOGRAPHICS_RESET = 'DEMOGRAPHICS_RESET';
export const DEMOGRAPHICS_FAIL = 'DEMOGRAPHICS_FAIL';

export const BUDGET_GENERATE_REQUEST = 'BUDGET_GENERATE_REQUEST';
export const BUDGET_GENERATE_SUCCESS = 'BUDGET_GENERATE_SUCCESS';
export const BUDGET_GENERATE_FAIL = 'BUDGET_GENERATE_FAIL';

export const SCORES_GENERATE_REQUEST = 'SCORES_GENERATE_REQUEST';
export const SCORES_GENERATE_SUCCESS = 'SCORES_GENERATE_SUCCESS';
export const SCORES_GENERATE_FAIL = 'SCORES_GENERATE_FAIL';

export const CLEAR_ERRORS = 'CLEAR_ERRORS';
