export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';

export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAIL = 'LOGOUT_FAIL';

export const BUDGET_GENERATE_REQUEST = 'BUDGET_GENERATE_REQUEST';
export const BUDGET_GENERATE_SUCCESS = 'BUDGET_GENERATE_SUCCESS';
export const BUDGET_GENERATE_FAIL = 'BUDGET_GENERATE_FAIL';

export const SCORES_GENERATE_REQUEST = 'SCORES_GENERATE_REQUEST';
export const SCORES_GENERATE_SUCCESS = 'SCORES_GENERATE_SUCCESS';
export const SCORES_GENERATE_FAIL = 'SCORES_GENERATE_FAIL';

// export const UPDATE_PROFILE_REQUEST = 'UPDATE_PROFILE_REQUEST';
// export const UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS';
// export const UPDATE_PROFILE_RESET = 'UPDATE_PROFILE_RESET';
// export const UPDATE_PROFILE_FAIL = 'UPDATE_PROFILE_FAIL';

// export const UPDATE_TICKET_REQUEST = 'UPDATE_TICKET_REQUEST';
// export const UPDATE_TICKET_SUCCESS = 'UPDATE_TICKET_SUCCESS';
// export const UPDATE_TICKET_RESET = 'UPDATE_TICKET_RESET';
// export const UPDATE_TICKET_FAIL = 'UPDATE_TICKET_FAIL';

export const CLEAR_ERRORS = 'CLEAR_ERRORS';
