export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';

export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAIL = 'LOGOUT_FAIL';

// export const LOAD_USER_REQUEST_TODO = 'LOAD_USER_REQUEST_TODO';
// export const LOAD_USER_SUCCESS_TODO = 'LOAD_USER_SUCCESS_TODO';
// export const LOAD_USER_FAIL_TODO = 'LOAD_USER_FAIL_TODO';

// export const LOAD_USER_REQUEST_INPROCCESS = 'LOAD_USER_REQUEST_INPROCCESS';
// export const LOAD_USER_SUCCESS_INPROCCESS = 'LOAD_USER_SUCCESS_INPROCCESS';
// export const LOAD_USER_FAIL_INPROCCESS = 'LOAD_USER_FAIL_INPROCCESS';

// export const UPDATE_PROFILE_REQUEST = 'UPDATE_PROFILE_REQUEST';
// export const UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS';
// export const UPDATE_PROFILE_RESET = 'UPDATE_PROFILE_RESET';
// export const UPDATE_PROFILE_FAIL = 'UPDATE_PROFILE_FAIL';

// export const UPDATE_TICKET_REQUEST = 'UPDATE_TICKET_REQUEST';
// export const UPDATE_TICKET_SUCCESS = 'UPDATE_TICKET_SUCCESS';
// export const UPDATE_TICKET_RESET = 'UPDATE_TICKET_RESET';
// export const UPDATE_TICKET_FAIL = 'UPDATE_TICKET_FAIL';

export const CLEAR_ERRORS = 'CLEAR_ERRORS';
